# -*- coding: utf-8 -*-
"""Project 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YGOXCdavom8VSLr5maT3usPKI6maVZEK

**PANDAS**

Import Pandas
"""

import pandas as pd

"""**Series Data**"""

age = pd.Series([50,30,40,60])
print(age)

"""**Data Frame**"""

age = pd.Series([50,30,40,60])
date=pd.DataFrame(age)
print(date)

data={
      "product":['laptop','Mobile',"Mouse"],
      "Price":[20000,15000,200]
}

pd.DataFrame(data)

"""**Data Load**"""

df = pd.read_csv('/content/student_sql_python_practice_100.csv')

df.head()

df.tail()

"total_record:", df.shape[0]

print("total_record:", df.shape[0])

df.info()

df.describe()

df.isnull()

df.isnull().sum()

df.columns

df["GPA"].mean()

print("Average_GPA: " , df['GPA'].mean() )